server:
  port: 8888
spring:
  application:
    name: config-server
#  datasource:
#    username: dbuser
#    password: {cipher}FKSAJDFGYOS8F7GLHAKERGFHLSAJ
  security:
    basic:
      enabled: true
    user:
      name: configuser
      password: configPass$1234
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anji4246/app-config
          force-pull: true # pull the latest code from GIT incase the local repo has some issues and couldn't able to update the repo
          skipSslValidation: true # Git Server SSL validation can be disabled
          timeout: 10 #HTTP connection timeout (In Seconds)
          username: *****
          password: ******